# Generated by Django 5.2.4 on 2025-08-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Startup_app', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
